SELECT so.ACADEMIC_PERIOD, so.COURSE_IDENTIFICATION, so.COURSE_REFERENCE_NUMBER , so.OFFERING_NUMBER, so.TITLE_LONG_DESC, so.MIN_CONTACT_HOURS, so.MAX_CONTACT_HOURS, 		so.INSTRUCTION_METHOD_DESC, so.MAXIMUM_ENROLLMENT, so.ACTUAL_ENROLLMENT, so.PRIMARY_INSTRUCTOR_FIRST_NAME, so.PRIMARY_INSTRUCTOR_LAST_NAME, so.PRIMARY_INSTRUCTOR_ID,
mt.START_DATE, mt.END_DATE, mt.BEGIN_TIME, mt.END_TIME, mt. BUILDING, mt.ROOM, mt.MONDAY_IND, mt.TUESDAY_IND, mt.WEDNESDAY_IND, mt.THURSDAY_IND, mt.FRIDAY_IND, mt.SATURDAY_IND, mt.SUNDAY_IND 
FROM ODSMGR.SCHEDULE_OFFERING so 
LEFT JOIN ODSMGR.MEETING_TIME mt ON so.COURSE_REFERENCE_NUMBER = mt.COURSE_REFERENCE_NUMBER AND so.ACADEMIC_PERIOD = mt.ACADEMIC_PERIOD  
WHERE 	so.ACADEMIC_PERIOD = 202660 and 
		(so.SUBJECT = 'PSYC' or so.SUBJECT = 'BAT' or so.SUBJECT = 'CARE') and 
		so.STATUS = 'A'